### PR TITLE
feat: allow customizable workspace service account annotations

### PR DESCRIPTION
**Pull request by coadler**

### CODE REVIEW

**Review by kylecarbs — COMMENTED** [review]
Who's asking for this? What's the use case?

**Comment by coadler** [comment]
[ch14469]

**Comment by coadler** [comment]
sorry, see clubhouse ticket

**Comment by jawnsy** [comment]
@coadler If we stop applying a service account, can the annotations be added on the `default` service account to fulfill this need? Is Discord using the service account token to do something? Is it possible for them to implement this using an admission controller to modify our workspace pods?

**Comment by kylecarbs** [comment]
@coadler can I close this?

**Pull request closed without merging**
