### PR TITLE
feat: allow specifying extra labels on the coderd deployment (#182)

### PR DESCRIPTION
**Pull request by johnstcn**
cherry-pick for 1.26; this is so we can update the helm submodule with just this specific change

### CODE REVIEW

**Review by deansheather — APPROVED** [review]

**Review by jawnsy — APPROVED** [review]

**Comment by johnstcn** [comment]
Leaving this open for probably around a month.

**Review by coadler — APPROVED** [review]

**Comment by jawnsy** [comment]
@johnstcn Do we still need this, or can it be closed?

**Comment by johnstcn** [comment]
@deansheather Should I leave this open for longer, or should we close it?

**Comment by deansheather** [comment]
Seems like it's unnecessary anymore, it's probably included in 1.27 now right?

**Comment by johnstcn** [comment]
Yep should be. Closing.

**Pull request closed without merging**
